#!/bin/bash
#
# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2017 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -z "$1" ]] && exit 1
[[ -z "$2" ]] && exit 1

gen_bar()
{
  local b
  local i
  local m
  local n
  local t

  declare -a bb

  [[ -z "$1" ]] && exit 1
  [[ -z "$2" ]] && exit 1

  for i in {0..5}
  do
    bb[$i]=0
  done

  i=0
  for t in 10 20 30 40 50 60
  do
    m=$(( t - 5 ))
    [[ "$m" -ge "$1" && "$m" -le "$2" ]] && bb[$i]=1
    [[ "$t" -ge "$1" && "$t" -le "$2" ]] && bb[$i]=2
    i=$((i+1))
  done

  n=$(echo "${bb[@]}" | tr -d ' ')
  b=$(echo "$n" | sed 's/0/□/g' | sed 's/1/▨/g' | sed 's/2/▣/g' )

  echo -n "$b "
}

gen_first()
{
  echo -n "$H1 "
  gen_bar "$R1" 60
}

gen_last()
{
  echo -n "$H2 "
  gen_bar 0 "$R2"
}

gen_between()
{
  local d
  local n
  local h

  d=$((H2-H1))

  if [[ "$d" -ge 2 ]]
  then
    n=$((d-1))
    for i in $(seq 1 "$n")
    do
      h=$((H1+i))
      echo -n "$h "
      gen_bar 0 60
    done
  fi
}

H1=$(echo "$1" | cut -d: -f1 | sed 's/^0//g')
M1=$(echo "$1" | cut -d: -f2 | sed 's/^0//g')
H2=$(echo "$2" | cut -d: -f1 | sed 's/^0//g')
M2=$(echo "$2" | cut -d: -f2 | sed 's/^0//g')

R1=$(( m = (M1+2)/5, m *= 5))
R2=$(( m = (M2+2)/5, m *= 5))

if [[ "$H2" -gt "$H1" ]]
then
  gen_first
  gen_between
  gen_last
else
  echo -n "$H1 "
  gen_bar "$R1" "$R2"
fi

