#!/bin/sh

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# BASED ON: https://unix.stackexchange.com/questions/183178/how-to-sum-time-using-bash#183321

# EXAMPLE
#
# timesum 00:10 00:40 00:25
# 01:15

EPOCH='1970-01-01'
SUM=0

for i in $@
do
  SUM="$(date -u -d "$EPOCH $i" +%s) + $SUM"
done

TOTAL=$(echo "$SUM" | bc)

date -u -d "$EPOCH $TOTAL sec" "+%H:%M"
