#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# BASED ON: https://unix.stackexchange.com/questions/183178/how-to-sum-time-using-bash#183321

# EXAMPLE
#
# timesum 00:10 00:40 00:25
# 01:15

EPOCH='1970-01-01'
SUM=0

for i in $@
do
  HS="$(echo "$i" | cut -d: -f1 | sed 's/^0//g')"
  MS="$(echo "$i" | cut -d: -f2)"
  HS=$((HS*3600))
  MS=$(echo $MS*60 | bc)
  SUM="$HS + $MS + $SUM"
done

if [[ -z "$SUM" ]]
then
  echo '00:00' && exit 0
fi

TOTAL=$(echo "$SUM" | bc)
HHMM="$(date -u '+%H:%M' -d @${TOTAL})"

if [[ $TOTAL -ge 86400 ]]
then

  DAYS="$((TOTAL/86400))"
  TDAYS="$((DAYS*24))"
  HH="$(echo "$HHMM" | cut -d: -f1 | sed 's/^0//g')"
  MM="$(echo "$HHMM" | cut -d: -f2)"
  TH="$((HH+TDAYS))"
  HM="$(printf "%02s:%02s" "$TH" "$MM")"
  echo "$HM"

else

  date -u -d "$EPOCH $TOTAL sec" "+%H:%M"

fi
